feat: add support for dart and flutter package MasonBundles
VeryGoodOpenSource/very_good_cli pull request #154
Opened 2021-07-20 20:26 UTC by denangelov

## Description

Add dart and flutter package MasonBundles and adapt CLI to support specifying the template to use for generation

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2021-07-20 22:10 UTC, felangel commented on lib/src/commands/create.dart
> +        allowed: _templates.expand((element) => [element.name]).toList(),
```suggestion
        allowed: _templates.map((element) => element.name).toList(),
```

2021-07-20 22:13 UTC, felangel commented on lib/src/dart_cli.dart
> +class _Cmd {
since this code is the exact same across the flutter_cli and dart_cli can we extract and reuse it?

2021-07-20 22:13 UTC, felangel commented on lib/src/templates/template.dart
> +      {required this.name, required this.bundle, required this.help});
```suggestion
      {required this.name, required this.bundle, required this.help,});
```

2021-07-20 22:13 UTC, felangel commented on lib/src/templates/template.dart
> +  /// The name associated with this template
```suggestion
  /// The name associated with this template.
```

2021-07-20 22:13 UTC, felangel commented on lib/src/templates/template.dart
> +      : super(name: 'dart_pkg', bundle: dartPackageBundle, help: '');
```suggestion
      : super(name: 'dart_pkg', bundle: dartPackageBundle, help: '',);
```
can we provide a help message?

2021-07-20 22:14 UTC, felangel commented on lib/src/templates/template.dart
> +      : super(name: 'flutter_pkg', bundle: flutterPackageBundle, help: '');
```suggestion
      : super(name: 'flutter_pkg', bundle: flutterPackageBundle, help: '',);
```
can we provide a help message?

2021-07-20 22:14 UTC, felangel commented on lib/src/templates/template.dart
> +  CoreTemplate() : super(name: 'core', bundle: veryGoodCoreBundle, help: '');
can we provide a help message?

2021-07-20 22:15 UTC, felangel requested changes
See comments also we need to write unit tests for the new templates 👍

2021-07-23 15:37 UTC, orestesgaolin commented on test/src/commands/create_test.dart
> +  'Creates a new very good flutter project in the specified directory.\n'
we need to update the README.md as well

2021-07-23 16:02 UTC, felangel commented on lib/src/commands/create.dart
> +/// `very_good create` command creates a project from a MasonBundle template.
```suggestion
/// `very_good create` command creates code from various built-in templates.
```

2021-07-23 16:02 UTC, felangel commented on lib/src/commands/create.dart
> +        help: 'The brick template used to generate this new project.',
```suggestion
        help: 'The template used to generate this new project.',
```

2021-07-23 16:06 UTC, felangel commented on lib/src/flutter_cli.dart
> +/// Command for Dart and Flutter CLI
```suggestion
/// Abstraction for running commands via command-line.
```

2021-07-23 16:09 UTC, felangel commented on lib/src/flutter_cli.dart
> +  /// Runs the specific command
```suggestion
  /// Runs the specified [cmd] with the provided [args].
```

2021-07-23 16:10 UTC, felangel commented on lib/src/templates/dart_package_bundle.dart
> +      "path": ".DS_Store",
.DS_Store should be ignored and not be included in the bundle.

2021-07-23 16:10 UTC, felangel commented on lib/src/templates/flutter_package_bundle.dart
> +      "path": ".DS_Store",
same here

2021-07-23 16:11 UTC, felangel commented on lib/src/templates/template.dart
> +  /// The MasonBundle used to generate this template.
```suggestion
  /// The [MasonBundle] used to generate this template.
```

2021-07-23 16:11 UTC, felangel commented on lib/src/templates/template.dart
> +  /// The tasks to run post generation for the specific MasonBundle.
```suggestion
  /// Callback invoked after template generation has completed.
```

2021-07-23 16:12 UTC, felangel commented on lib/src/templates/template.dart
> +/// {@template template}
```suggestion
/// {@template dart_pkg_template}
```

2021-07-23 16:12 UTC, felangel commented on lib/src/templates/template.dart
> +  /// {@macro template}
```suggestion
  /// {@macro dart_pkg_template}
```

2021-07-23 16:12 UTC, felangel commented on lib/src/templates/template.dart
> +  /// The tasks to run post generation for the specific MasonBundle.
We don't need to have redundant docs here since this is override.
```suggestion
```

2021-07-23 16:13 UTC, felangel commented on lib/src/templates/template.dart
> +/// {@template template}
```suggestion
/// {@template flutter_pkg_template}
```

2021-07-23 16:13 UTC, felangel commented on lib/src/templates/template.dart
> +/// Dart class that represents a VeryGoodCLI dart package template.
```suggestion
/// Dart class that represents a VeryGoodCLI Flutter package template.
```

2021-07-23 16:13 UTC, felangel commented on lib/src/templates/template.dart
> +  /// {@macro template}
```suggestion
  /// {@macro flutter_pkg_template}
```

2021-07-23 16:13 UTC, felangel commented on lib/src/templates/template.dart
> +  /// The tasks to run post generation for the specific MasonBundle.
```suggestion
```

2021-07-23 16:47 UTC, felangel commented on lib/src/templates/template.dart
> +import 'package:very_good_cli/src/templates/very_good_core_bundle.dart';
```suggestion
import 'package:very_good_cli/src/templates/templates.dart';
```

2021-07-23 16:47 UTC, felangel commented on lib/src/templates/template.dart
> +/// Each template consists of a [MasonBundle]
```suggestion
/// Each template consists of a [MasonBundle], name,
```

2021-07-23 16:48 UTC, felangel commented on lib/src/templates/template.dart
> +/// Dart class that represents a VeryGoodCLI dart package template.
```suggestion
/// Dart class that represents a VeryGoodCLI core flutter application template.
```

2021-07-23 16:48 UTC, felangel commented on lib/src/templates/template.dart
> +  /// The tasks to run post generation for the specific MasonBundle.
```suggestion
```

2021-07-23 16:48 UTC, felangel commented on lib/src/templates/template.dart
> +/// {@template template}
```suggestion
/// {@template core_template}
```

2021-07-23 16:48 UTC, felangel commented on lib/src/templates/template.dart
> +  /// {@macro template}
```suggestion
  /// {@macro core_template}
```

2021-07-23 16:49 UTC, felangel commented on test/src/commands/create_test.dart
> +import 'package:very_good_cli/src/templates/very_good_core_bundle.dart';
```suggestion
import 'package:very_good_cli/src/templates/templates.dart';
```

2021-07-23 17:50 UTC, felangel approved these changes
LGTM :shipit:

2021-07-23 17:51 UTC, merged