Fix/recursive min coverage
VeryGoodOpenSource/very_good_cli pull request #647
Opened 2023-02-09 20:35 UTC by willhlas

## Description

Fixes bug where running `--min-coverage` with `--recursive` would not throw error if min coverage was not met.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-02-09 21:23 UTC, wolfenrain approved these changes

2023-02-09 22:41 UTC, felangel commented on lib/src/cli/flutter_cli.dart
> +          if (collectCoverage) {
Can we add a test for this fix to ensure it doesn't happen again?

2023-02-09 22:41 UTC, felangel requested changes
Can we add a test for this fix to ensure it doesn't happen again?

2023-02-16 10:45 UTC, renancaraujo approved these changes

2023-02-16 17:38 UTC, felangel submitted a review, later dismissed

2023-02-21 12:21 UTC, wolfenrain approved these changes

2023-02-21 12:21 UTC, merged